package store

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"time"
)

// DB is the package‑level SQLite connection used by all store functions.
// It must be set (e.g. via main.go) before calling any CRUD operation.
var DB *sql.DB

// List returns all links ordered by ID ascending.
func List(ctx context.Context) ([]Link, error) {
	if DB == nil {
		return nil, errors.New("store DB not initialized")
	}
	rows, err := DB.QueryContext(ctx, "SELECT id, title, url, created_at FROM links ORDER BY id ASC")
	if err != nil {
		return nil, fmt.Errorf("list links: %w", err)
	}
	defer rows.Close()

	var links []Link
	for rows.Next() {
		var l Link
		if err := rows.Scan(&l.ID, &l.Title, &l.URL, &l.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan link: %w", err)
		}
		links = append(links, l)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate links: %w", err)
	}
	return links, nil
}

// Create inserts a new link after validating title and URL.
// It returns the created Link, including its autogenerated ID and timestamp.
func Create(ctx context.Context, title, url string) (Link, error) {
	if DB == nil {
		return Link{}, errors.New("store DB not initialized")
	}
	if err := validateTitle(title); err != nil {
		return Link{}, err
	}
	if err := validateURL(url); err != nil {
		return Link{}, err
	}

	const insertSQL = "INSERT INTO links (title, url, created_at) VALUES (?, ?, ?)"
	createdAt := time.Now().UTC().Format(time.RFC3339)
	res, err := DB.ExecContext(ctx, insertSQL, title, url, createdAt)
	if err != nil {
		return Link{}, fmt.Errorf("create link: %w", err)
	}
	id, err := res.LastInsertId()
	if err != nil {
		return Link{}, fmt.Errorf("retrieve last insert id: %w", err)
	}
	return Link{
		ID:        id,
		Title:     title,
		URL:       url,
		CreatedAt: createdAt,
	}, nil
}

// Delete removes a link by its ID. Deleting a non‑existent ID is not an error.
func Delete(ctx context.Context, id int64) error {
	if DB == nil {
		return errors.New("store DB not initialized")
	}
	_, err := DB.ExecContext(ctx, "DELETE FROM links WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("delete link: %w", err)
	}
	return nil
}

// validateTitle ensures the title is non‑empty and ≤ 200 Unicode runes.
func validateTitle(title string) error {
	if strings.TrimSpace(title) == "" {
		return errors.New("title cannot be empty")
	}
	if runeCount(title) > 200 {
		return errors.New("title exceeds 200 characters")
	}
	return nil
}

// validateURL checks that the URL starts with http:// or https://.
func validateURL(url string) error {
	if strings.HasPrefix(url, "http://") || strings.HasPrefix(url, "https://") {
		return nil
	}
	return errors.New("url must start with http:// or https://")
}

// runeCount returns the number of runes in a string.
func runeCount(s string) int {
	return len([]rune(s))
}
